In [83]:
import torch

w=torch.Tensor([[-1,2,3,4], [5,6, 7,8]])
print(w, w.shape)
s=torch.max(w, dim=1)[0]
print(s, s.shape)
s = s.unsqueeze(dim=1)
scaled = w.data / s
print(scaled, scaled.shape)

tensor([[-1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]]) torch.Size([2, 4])
tensor([4., 8.]) torch.Size([2])
tensor([[-0.2500,  0.5000,  0.7500,  1.0000],
        [ 0.6250,  0.7500,  0.8750,  1.0000]]) torch.Size([2, 4])


In [84]:
s = s.unsqueeze(dim=1)
s.shape


torch.Size([2, 1, 1])

In [85]:
w.data / s

tensor([[[-0.2500,  0.5000,  0.7500,  1.0000],
         [ 1.2500,  1.5000,  1.7500,  2.0000]],

        [[-0.1250,  0.2500,  0.3750,  0.5000],
         [ 0.6250,  0.7500,  0.8750,  1.0000]]])

In [86]:
w=torch.linspace(-5, 6, 24).reshape(4,6)
print(w, w.shape)
s=torch.Tensor([-2, 2, 3, -3, 3, 3]).reshape(3, 2)
print(s, s.shape)
r = torch.repeat_interleave(s, 2, dim=1)
print(r, r.shape)

tensor([[-5.0000, -4.5217, -4.0435, -3.5652, -3.0870, -2.6087],
        [-2.1304, -1.6522, -1.1739, -0.6957, -0.2174,  0.2609],
        [ 0.7391,  1.2174,  1.6957,  2.1739,  2.6522,  3.1304],
        [ 3.6087,  4.0870,  4.5652,  5.0435,  5.5217,  6.0000]]) torch.Size([4, 6])
tensor([[-2.,  2.],
        [ 3., -3.],
        [ 3.,  3.]]) torch.Size([3, 2])
tensor([[-2., -2.,  2.,  2.],
        [ 3.,  3., -3., -3.],
        [ 3.,  3.,  3.,  3.]]) torch.Size([3, 4])


In [87]:

s.repeat(2)

RuntimeError: Number of dimensions of repeat dims can not be smaller than number of dimensions of tensor

In [ ]:
w=torch.linspace(-5, 6, 24).reshape(4,6)
print(w, w.shape)
s=torch.Tensor([-2, 2, 3, -3, 3, 3]).reshape(3, 2)
print(s, s.shape)
r = torch.repeat_interleave(s, 2, dim=1)

print(w, w.shape)
scale = []
columns = w.shape[1]
group_size = 3
assert columns % group_size == 0
for i1 in range(0, columns, group_size):
    i2 = i1 + group_size
    s_column = torch.min(w[:, i1:i2], dim=1)[0]
    s_column = s_column.unsqueeze(dim=1)
    scale.append(s_column)
scale = torch.cat(scale, dim=1)
scale = torch.repeat_interleave(scale, group_size, dim=1)
print(scale, scale.shape)
res = w/scale
print(res, res.shape)




tensor([[-5.0000, -4.5217, -4.0435, -3.5652, -3.0870, -2.6087],
        [-2.1304, -1.6522, -1.1739, -0.6957, -0.2174,  0.2609],
        [ 0.7391,  1.2174,  1.6957,  2.1739,  2.6522,  3.1304],
        [ 3.6087,  4.0870,  4.5652,  5.0435,  5.5217,  6.0000]]) torch.Size([4, 6])
tensor([[-5.0000, -5.0000, -5.0000, -3.5652, -3.5652, -3.5652],
        [-2.1304, -2.1304, -2.1304, -0.6957, -0.6957, -0.6957],
        [ 0.7391,  0.7391,  0.7391,  2.1739,  2.1739,  2.1739],
        [ 3.6087,  3.6087,  3.6087,  5.0435,  5.0435,  5.0435]]) torch.Size([4, 6])
tensor([[ 1.0000,  0.9043,  0.8087,  1.0000,  0.8659,  0.7317],
        [ 1.0000,  0.7755,  0.5510,  1.0000,  0.3125, -0.3750],
        [ 1.0000,  1.6471,  2.2941,  1.0000,  1.2200,  1.4400],
        [ 1.0000,  1.1325,  1.2651,  1.0000,  1.0948,  1.1897]]) torch.Size([4, 6])


In [ ]:
scale[:10,0]


tensor([-5.0000, -2.1304,  0.7391,  3.6087])

In [ ]:
scale_r = torch.repeat_interleave(scale, 2, dim=1)
print(scale_r, scale_r.shape)
w/scale_r

tensor([[-4., -4., -2., -2.],
        [ 0.,  0.,  2.,  2.],
        [ 4.,  4.,  6.,  6.]]) torch.Size([3, 4])


tensor([[1.2500, 1.0000, 1.5000, 1.0000],
        [  -inf,    nan, 0.5000, 1.0000],
        [0.7500, 1.0000, 0.8333, 1.0000]])

In [ ]:
torch.cat(scale, dim=0)

tensor([-4.,  0.,  4., -2.,  2.,  6.])